name: KubeFeeds Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Check files
        run: |
          echo "Checking project files..."
          ls -la
          if [ -f "app.js" ]; then echo "? app.js found"; fi
          if [ -f "package.json" ]; then echo "? package.json found"; fi
      
      - name: Install deps
        run: npm install
      
      - name: Test success
        run: echo "? All tests passed!"