name: KubeFeeds Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  basic-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: List files
      run: |
        echo "Repository contents:"
        ls -la
        echo ""
        echo "Checking essential files..."
        
        if [ -f "app.js" ]; then
          echo "? app.js found"
        else
          echo "? app.js missing"
        fi
        
        if [ -f "package.json" ]; then
          echo "? package.json found"
          echo "Package info:"
          head -10 package.json
        else
          echo "? package.json missing"
        fi
        
        if [ -f "README.md" ]; then
          echo "? README.md found"
        else
          echo "? README.md missing"
        fi
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Verify Node.js setup
      run: |
        echo "Node.js version:"
        node --version
        echo "npm version:"
        npm --version
        echo "Node.js setup successful"
    
    - name: Check package.json validity
      run: |
        if [ -f "package.json" ]; then
          echo "Validating package.json..."
          node -e "
            try {
              const pkg = require('./package.json');
              console.log('package.json is valid JSON');
              console.log('Name:', pkg.name || 'Not specified');
              console.log('Version:', pkg.version || 'Not specified');
              console.log('Main file:', pkg.main || 'Not specified');
              process.exit(0);
            } catch (error) {
              console.error('package.json validation failed:', error.message);
              process.exit(1);
            }
          "
        else
          echo "package.json not found"
        fi
    
    - name: Basic project validation
      run: |
        echo "All basic validations completed successfully!"
        echo ""
        echo "Summary:"
        echo "- Repository: ${{ github.repository }}"
        echo "- Branch: ${{ github.ref_name }}"
        echo "- Commit: ${{ github.sha }}"
        echo "- Event: ${{ github.event_name }}"
        echo ""
        echo "Project structure looks good!"

  simple-test:
    needs: basic-validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Test npm install
      run: |
        echo "Testing npm install..."
        npm install --verbose
        echo "npm install successful"
    
    - name: Verify installation
      run: |
        echo "Checking node_modules..."
        if [ -d "node_modules" ]; then
          echo "node_modules directory created"
          echo "Installed packages:"
          ls node_modules | head -10
        else
          echo "node_modules not found"
          exit 1
        fi
    
    - name: Success
      run: |
        echo "All tests passed!"
        echo ""
        echo "The KubeFeeds project is ready for development."
        echo ""
        echo "Next steps:"
        echo "1. Clone the repository locally"
        echo "2. Run 'npm install'"
        echo "3. Run 'npm start'"
        echo "4. Visit http://localhost:3000"